[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["@netlify/functions"]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  included_files = [
    "netlify/functions/**/*.ts",
    "src/**/*.ts",
    "!**/node_modules/**",
    "!**/models/**",
    "!**/transformers-cache/**"
  ]

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  publish = "dist"
